name: 'CI' #set whatevername you want to your github job
on: {} # set the events you would like to trigger this job
jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.1 # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: cloud-computing-api-stg # you aplication name
          dockerfile_path: './WebAPI' # set the path to the folder wher the Dokerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web
  build-spa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.1 # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
          app_name: cloud-computing-spa-stg # you aplication name
          dockerfile_path: './SPA' # set the path to the folder wher the Dokerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web
    
